## Aponti Academy - Indicadores e Fatores Associados a Acidentes de Trânsito 2025

### Base de Acidentes (Acidentes2025.csv)

#### Módulo 6:

Análise Exploratória, Indicadores e Fatores Associados para um contexto de análise de dados em acidentes de trânsito com indicadores - Ranking e séries - análise bivarida orientada a um alvo com combinações de fatores gráficos e síntese interpretativa

 #### Base de dados:

com cerca de 72530 acidentes, nós periodos de 2025-01-01 a 2025-11-02, apresento as seguintes colunas na base de dados

- id = Identificador único do acidente na base de dados. 
- data_inversa = Data da ocorrência do acidente.
- dia_semana = semana ocorrida no acidente 
- horario = Horário da ocorrência do acidente.
- uf = Unidade da Federação (estado) onde ocorreu o acidente.
- br = Número da rodovia federal (BR) onde ocorreu o acidente.
- km = Quilômetro da rodovia onde ocorreu o acidente. 
- municipio = Município da ocorrência do acidente. 
- causa_acidente = Causa presumível do acidente identificada pela PRF. 
- tipo_acidente = Tipo do acidente (colisão frontal, saída de pista, capotamento, atropelamento etc.)
- classificacao_acidente = Classificação da gravidade do acidente (sem vítimas, com vítimas feridas ou com vítimas fatais).
- fase_dia = Período do dia em que ocorreu o acidente (amanhecer, pleno dia, anoitecer, plena noite etc.).
- sentido_via = Sentido da via no local do acidente (crescente ou decrescente). 
- condicao_metereologica = Condição climática no momento do acidente (céu claro, chuva, neblina, vento etc.).

- tipo_pista = Tipo de pista da rodovia (simples, dupla ou múltipla). 
- tracado_via = Característica geométrica da via (reta, curva, cruzamento, viaduto, interseção etc.). 
- uso_solo = Classificação da área onde ocorreu o acidente (urbana ou rural). 
- pessoas = Quantidade total de pessoas envolvidas na ocorrência. 
- mortos = Quantidade de pessoas que morreram em decorrência do acidente. 
- feridos_leves = Quantidade de pessoas com ferimentos leves. 
- feridos_graves = Quantidade de pessoas com ferimentos graves. 
- ilesos = Quantidade de pessoas envolvidas que não sofreram ferimentos. 
- ignorados = Quantidade de pessoas cujo estado físico não foi identificado ou informado. 
- feridos = Total de pessoas feridas (soma de feridos leves e graves). 
- veiculos = Quantidade total de veículos envolvidos no acidente. 
- latitude = Coordenada geográfica de latitude do local do acidente. 
- longitude = Coordenada geográfica de longitude do local do acidente. 
- regional = Superintendência Regional da PRF responsável pela ocorrência. 
- delegacia = Delegacia da PRF responsável pelo atendimento da ocorrência. 
- uop = Unidade Operacional da PRF responsável pelo registro ou atendimento da ocorrência.

#### Problema analítico central

- Como as variáveis temporais (data, horário e dia da semana), ambientais (condições meteorológicas e fase do dia), características da rodovia (tipo de pista, traçado da via e sentido da via) e fatores geográficos (UF, município, BR e quilômetro) influenciam a ocorrência e a classificação dos acidentes registrados pela Polícia Rodoviária Federal em 2025?

#### Objetivo Geral

Analisar os fatores temporais, ambientais, estruturais e geográficos associados aos acidentes registrados pela Polícia Rodoviária Federal em 2025, identificando padrões que contribuam para a compreensão da frequência, do tipo e da gravidade das ocorrências.

#### Importação das bibliotecas

In [2]:
import pandas as pd
import numpy as np

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/home/gustavo/anaconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/gustavo/anaconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/gustavo/anaconda3/lib/python3.9/site-packages/ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "/home/gustavo/anaconda3/lib/python3.9/site-packages/traitlets/config/application.py", line 846, in launch_instance
    app.start()
  File "/home/gustavo/anaconda3/lib/python3.9/site-packages/ipykernel/kernelapp.py", line 712, in start
    self.io_loop.start()
  File "/home/gustavo/anaconda3/lib/python3.9/site-packages/tornado/platform/asyncio.py", line 199, in start
    self.asyncio_loop.run_forever()
  File "/home/gustavo/anaconda3/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/home/gustavo/anaconda3/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/home/gustavo/anaconda3/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/gustavo/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 510, in dispatch_queue
    await self.process_one()
  File "/home/gustavo/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 499, in process_one
    await dispatch(*args)
  File "/home/gustavo/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 406, in dispatch_shell
    await result
  File "/home/gustavo/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 730, in execute_request
    reply_content = await reply_content
  File "/home/gustavo/anaconda3/lib/python3.9/site-packages/ipykernel/ipkernel.py", line 390, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/home/gustavo/anaconda3/lib/python3.9/site-packages/ipykernel/zmqshell.py", line 528, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/home/gustavo/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 2914, in run_cell
    result = self._run_cell(
  File "/home/gustavo/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 2960, in _run_cell
    return runner(coro)
  File "/home/gustavo/anaconda3/lib/python3.9/site-packages/IPython/core/async_helpers.py", line 78, in _pseudo_sync_runner
    coro.send(None)
  File "/home/gustavo/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3185, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/home/gustavo/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3377, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/home/gustavo/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3457, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_3094/2162656668.py", line 1, in <module>
    import pandas as pd
  File "/home/gustavo/anaconda3/lib/python3.9/site-packages/pandas/__init__.py", line 49, in <module>
    from pandas.core.api import (
  File "/home/gustavo/anaconda3/lib/python3.9/site-packages/pandas/core/api.py", line 28, in <module>
    from pandas.core.arrays import Categorical
  File "/home/gustavo/anaconda3/lib/python3.9/site-packages/pandas/core/arrays/__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "/home/gustavo/anaconda3/lib/python3.9/site-packages/pandas/core/arrays/arrow/__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "/home/gustavo/anaconda3/lib/python3.9/site-packages/pandas/core/arrays/arrow/array.py", line 53, in <module>
    from pandas.core import (
  File "/home/gustavo/anaconda3/lib/python3.9/site-packages/pandas/core/ops/__init__.py", line 8, in <module>
    from pandas.core.ops.array_ops import (
  File "/home/gustavo/anaconda3/lib/python3.9/site-packages/pandas/core/ops/array_ops.py", line 56, in <module>
    from pandas.core.computation import expressions
  File "/home/gustavo/anaconda3/lib/python3.9/site-packages/pandas/core/computation/expressions.py", line 21, in <module>
    from pandas.core.computation.check import NUMEXPR_INSTALLED
  File "/home/gustavo/anaconda3/lib/python3.9/site-packages/pandas/core/computation/check.py", line 5, in <module>
    ne = import_optional_dependency("numexpr", errors="warn")
  File "/home/gustavo/anaconda3/lib/python3.9/site-packages/pandas/compat/_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/gustavo/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/gustavo/anaconda3/lib/python3.9/site-packages/numexpr/__init__.py", line 24, in <module>
    from numexpr.interpreter import MAX_THREADS, use_vml, __BLOCK_SIZE1__

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/home/gustavo/anaconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/gustavo/anaconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/gustavo/anaconda3/lib/python3.9/site-packages/ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "/home/gustavo/anaconda3/lib/python3.9/site-packages/traitlets/config/application.py", line 846, in launch_instance
    app.start()
  File "/home/gustavo/anaconda3/lib/python3.9/site-packages/ipykernel/kernelapp.py", line 712, in start
    self.io_loop.start()
  File "/home/gustavo/anaconda3/lib/python3.9/site-packages/tornado/platform/asyncio.py", line 199, in start
    self.asyncio_loop.run_forever()
  File "/home/gustavo/anaconda3/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/home/gustavo/anaconda3/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/home/gustavo/anaconda3/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/gustavo/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 510, in dispatch_queue
    await self.process_one()
  File "/home/gustavo/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 499, in process_one
    await dispatch(*args)
  File "/home/gustavo/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 406, in dispatch_shell
    await result
  File "/home/gustavo/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 730, in execute_request
    reply_content = await reply_content
  File "/home/gustavo/anaconda3/lib/python3.9/site-packages/ipykernel/ipkernel.py", line 390, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/home/gustavo/anaconda3/lib/python3.9/site-packages/ipykernel/zmqshell.py", line 528, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/home/gustavo/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 2914, in run_cell
    result = self._run_cell(
  File "/home/gustavo/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 2960, in _run_cell
    return runner(coro)
  File "/home/gustavo/anaconda3/lib/python3.9/site-packages/IPython/core/async_helpers.py", line 78, in _pseudo_sync_runner
    coro.send(None)
  File "/home/gustavo/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3185, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/home/gustavo/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3377, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/home/gustavo/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3457, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_3094/2162656668.py", line 1, in <module>
    import pandas as pd
  File "/home/gustavo/anaconda3/lib/python3.9/site-packages/pandas/__init__.py", line 49, in <module>
    from pandas.core.api import (
  File "/home/gustavo/anaconda3/lib/python3.9/site-packages/pandas/core/api.py", line 28, in <module>
    from pandas.core.arrays import Categorical
  File "/home/gustavo/anaconda3/lib/python3.9/site-packages/pandas/core/arrays/__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "/home/gustavo/anaconda3/lib/python3.9/site-packages/pandas/core/arrays/arrow/__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "/home/gustavo/anaconda3/lib/python3.9/site-packages/pandas/core/arrays/arrow/array.py", line 67, in <module>
    from pandas.core.arrays.masked import BaseMaskedArray
  File "/home/gustavo/anaconda3/lib/python3.9/site-packages/pandas/core/arrays/masked.py", line 61, in <module>
    from pandas.core import (
  File "/home/gustavo/anaconda3/lib/python3.9/site-packages/pandas/core/nanops.py", line 52, in <module>
    bn = import_optional_dependency("bottleneck", errors="warn")
  File "/home/gustavo/anaconda3/lib/python3.9/site-packages/pandas/compat/_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/gustavo/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/gustavo/anaconda3/lib/python3.9/site-packages/bottleneck/__init__.py", line 7, in <module>
    from .move import (move_argmax, move_argmin, move_max, move_mean, move_median,

AttributeError: _ARRAY_API not found

In [3]:
import matplotlib.pyplot as plt

#### Importação do módulo de formatação de eixos do matplotlib

In [4]:
# Usado para exibir os eixos dos gráficos em formato de porcentagem (%), facilitando a leitura 
import matplotlib.ticker as mtick

In [5]:
# Configuração de exibição de números decimais do pandas 
# Formata todos os números float exibidos em tabelas com separador de milhar e 2 casas decimais 
pd.set_option("display.float_format", lambda x: f"{x:,.2f}")

In [6]:
# Ajuste da resolução (DPI) padrão dos gráficos 
# Deixa os gráficos exibidos no notebook com melhor nitidez 
plt.rcParams["figure.dpi"] = 100

In [7]:
# Leitura do arquivo csv da base de dados 
# Carrega os 72530 registros de acidentes para o dataframe chamado "prf_acidentes_2025"
prf_acidentes_2025 = pd.read_csv("acidentes2025.csv", encoding="ISO-8859-1", sep=";")

In [8]:
# Conversão da coluna de data de texto para o tipo datetime 
# Necessário para permitir agrupamento por mês / ano e cálculos de série temporal 
prf_acidentes_2025["data_inversa"] = pd.to_datetime(prf_acidentes_2025["data_inversa"])

In [9]:
# Exibição do formato da base (linhas, colunas) 
# Primeira conferência: confirma que os 72530 acidentes e as 30 colunas foram carregados corretamente 
print(prf_acidentes_2025.shape)

(72529, 30)

In [10]:
# Exibição das 10 primeiras linhas da base 
# Permite uma inspeção visual inicial da estrutura e do contéudo dos dados 
prf_acidentes_2025.head(10)

,id,data_inversa,dia_semana,horario,uf,br,km,municipio,causa_acidente,tipo_acidente,...,feridos_graves,ilesos,ignorados,feridos,veiculos,latitude,longitude,regional,delegacia,uop
0,652493,2025-01-01,quarta-feira,06:20:00,SP,116,225,GUARULHOS,Reação tardia ou ineficiente do condutor,Tombamento,...,0,0,1,1,2,"-23,48586772","-46,54075317",SPRF-SP,DEL01-SP,UOP01-DEL01-SP
1,652519,2025-01-01,quarta-feira,07:50:00,CE,116,"546,2",PENAFORTE,Pista esburacada,Colisão frontal,...,0,1,4,1,6,"-7,812288","-39,08333306",SPRF-CE,DEL05-CE,UOP03-DEL05-CE
2,652522,2025-01-01,quarta-feira,08:45:00,PR,369,"88,2",CORNELIO PROCOPIO,Reação tardia ou ineficiente do condutor,Colisão traseira,...,0,2,0,3,2,"-23,182565","-50,637228",SPRF-PR,DEL07-PR,UOP05-DEL07-PR
3,652544,2025-01-01,quarta-feira,11:00:00,PR,116,74,CAMPINA GRANDE DO SUL,Reação tardia ou ineficiente do condutor,Saída de leito carroçável,...,0,4,0,1,2,"-25,36517687","-49,04223028",SPRF-PR,DEL01-PR,UOP02-DEL01-PR
4,652549,2025-01-01,quarta-feira,09:30:00,MG,251,471,FRANCISCO SA,Velocidade Incompatível,Colisão frontal,...,1,1,2,2,4,"-16,46801304","-43,43121303",SPRF-MG,DEL12-MG,UOP01-DEL12-MG
5,652569,2025-01-01,quarta-feira,10:40:00,MT,70,669,CACERES,Transitar na contramão,Colisão frontal,...,0,1,2,0,5,"-16,04148578","-57,25884017",SPRF-MT,DEL03-MT,UOP02-DEL03-MT
6,652573,2025-01-01,quarta-feira,12:23:00,RS,116,376,TAPES,Ausência de reação do condutor,Saída de leito carroçável,...,0,0,1,1,2,"-30,739714","-51,62594",SPRF-RS,DEL02-RS,UOP02-DEL02-RS
7,652617,2025-01-01,quarta-feira,17:45:00,SC,101,"207,4",SAO JOSE,Ausência de reação do condutor,Colisão traseira,...,0,1,0,1,2,"-27,60001226","-48,6226467",SPRF-SC,DEL01-SC,UOP01-DEL01-SC
8,652625,2025-01-01,quarta-feira,18:40:00,MG,116,"708,5",MURIAE,Velocidade Incompatível,Tombamento,...,0,0,1,0,2,"-21,16328873","-42,37968988",SPRF-MG,DEL07-MG,UOP02-DEL07-MG
9,652648,2025-01-01,quarta-feira,17:00:00,PE,407,"7,4",AFRANIO,Demais falhas mecânicas ou elétricas,Incêndio,...,0,2,0,0,1,"-8,47503105","-41,0137105",SPRF-PE,DEL06-PE,UOP02-DEL06-PE

#### Compreensão dos dados

- Antes de qualquer indicador, conferimos tipos, nulos e consistência - equivalente ao Bloco "Compreensão dos dados" do CRISP-DM que antecede este módulo.

In [11]:
# Exibição dos tipos de dados (dtype) de cada coluna. 
# Importante para confirmar se colunas numéricas (preço, quantidade) e de data foram 
# reconhecidos corretamente, e não interpretadas como texto (object) 

print("Tipos de dados: ") 
print(prf_acidentes_2025.dtypes)

Tipos de dados:
id                                 int64
data_inversa              datetime64[ns]
dia_semana                        object
horario                           object
uf                                object
br                                 int64
km                                object
municipio                         object
causa_acidente                    object
tipo_acidente                     object
classificacao_acidente            object
fase_dia                          object
sentido_via                       object
condicao_metereologica            object
tipo_pista                        object
tracado_via                       object
uso_solo                          object
pessoas                            int64
mortos                             int64
feridos_leves                      int64
feridos_graves                     int64
ilesos                             int64
ignorados                          int64
feridos                            int64
veiculos                           int64
latitude                          object
longitude                         object
regional                          object
delegacia                         object
uop                               object
dtype: object

In [12]:
# Contagem de valores ausentes (NaN) por coluna 
# Etapa obrigatória de qualidade de dados: identifica onde existem lacunas 
# antes de calcular qualquer indicador ou média 
print("\n Valores ausentes por coluna: ") 
print(prf_acidentes_2025.isna().sum())

 Valores ausentes por coluna:
id                         0
data_inversa               0
dia_semana                 0
horario                    0
uf                         0
br                         0
km                         0
municipio                  0
causa_acidente             0
tipo_acidente              0
classificacao_acidente     1
fase_dia                   0
sentido_via                0
condicao_metereologica     0
tipo_pista                 0
tracado_via                0
uso_solo                   0
pessoas                    0
mortos                     0
feridos_leves              0
feridos_graves             0
ilesos                     0
ignorados                  0
feridos                    0
veiculos                   0
latitude                   0
longitude                  0
regional                   2
delegacia                 22
uop                       38
dtype: int64

In [13]:
# Verificação do périodo coberto pela base 
# Mostra a menor e a maior data de acidente, delimitanto a janela temporal da análise 
print("\n Período coberto: ", prf_acidentes_2025['data_inversa'].min().date(), "a", prf_acidentes_2025["data_inversa"].max().date())

 Período coberto:  2025-01-01 a 2025-12-31

#### Status dos Acidentes com as colunas

- municipio
- causa_acidente
- tipo_acidente 
- classificacao_acidente 
- condicao_metereologica
- tipo_pista 
- tracado_via
- uso_solo

In [78]:
# Contagem de acidentes por município
# Primeira visão da variável que originará o alvo (pedido_problematico): 
# quantos acidentes poossui a parte de municipio
print("\nStatus de Acidentes por municipio")
print(prf_acidentes_2025["municipio"].value_counts().head(30))

Status de Acidentes por municipio
municipio
BRASILIA                 1011
DUQUE DE CAXIAS           847
SAO JOSE                  761
GUARULHOS                 742
CURITIBA                  702
BETIM                     682
RECIFE                    615
SERRA                     579
PALHOCA                   568
JOAO PESSOA               543
TERESINA                  499
SAO JOSE DOS PINHAIS      464
RIO DE JANEIRO            448
NOVA IGUACU               439
ANGRA DOS REIS            437
SAO JOSE DOS CAMPOS       413
FEIRA DE SANTANA          403
ANAPOLIS                  385
ITAJAI                    382
UBERABA                   366
ARAQUARI                  352
CAMPOS DOS GOYTACAZES     350
UBERLANDIA                349
LINHARES                  345
SAO GONCALO               337
NATAL                     325
CASCAVEL                  323
PORTO VELHO               319
SAO PAULO                 316
VITORIA DA CONQUISTA      314
Name: count, dtype: int64

In [15]:
# Contagem de acidentes por causa_acidente
# Primeira visão da variável que originará o alvo (pedido_problematico): 
# quantos acidentes poossui a parte de causa_acidente
print("\nStatus de Acidentes por causa de acidentes")
print(prf_acidentes_2025["causa_acidente"].value_counts())

Status de Acidentes por causa de acidentes
causa_acidente
Ausência de reação do condutor                               11469
Reação tardia ou ineficiente do condutor                     10799
Acessar a via sem observar a presença dos outros veículos     7097
Condutor deixou de manter distância do veículo da frente      4413
Velocidade Incompatível                                       4088
                                                             ...
Faróis desregulados                                              9
Redutor de velocidade em desacordo                               8
Semáforo com defeito                                             8
Sistema de drenagem ineficiente                                  2
Sinalização encoberta                                            2
Name: count, Length: 69, dtype: int64

In [16]:
# Contagem de acidentes por condição metereologica
# Primeira visão da variável que originará o alvo (pedido_problematico): 
# quantos acidentes poossui a parte de condição metereologica 
print("\nStatus de Acidentes por condições metereologicas")
print(prf_acidentes_2025["condicao_metereologica"].value_counts())

Status de Acidentes por condições metereologicas
condicao_metereologica
Céu Claro           46375
Nublado             11435
Chuva                6438
Sol                  4201
Garoa/Chuvisco       2422
Ignorado             1000
Nevoeiro/Neblina      553
Vento                 104
Neve                    1
Name: count, dtype: int64

In [17]:
# Contagem de acidentes por tipos de pistas
# Primeira visão da variável que originará o alvo (pedido_problematico): 
# quantos acidentes poossui a parte de por tipos de pistas
print("\nStatus de Acidentes por tipos de pistas")
print(prf_acidentes_2025["tipo_pista"].value_counts())

Status de Acidentes por tipos de pistas
tipo_pista
Simples     34733
Dupla       30782
Múltipla     7014
Name: count, dtype: int64

In [79]:
# Contagem de acidentes por tipos de pistas
# Primeira visão da variável que originará o alvo (pedido_problematico): 
# quantos acidentes poossui a parte de via
print("\nStatus de Acidentes por parte da via")
print(prf_acidentes_2025["tracado_via"].value_counts().head(20))

Status de Acidentes por parte da via
tracado_via
Reta                          40298
Curva                          8055
Reta;Declive                   2059
Reta;Aclive                    1963
Interseção de Vias             1735
Declive;Reta                   1492
Curva;Declive                  1430
Aclive;Reta                    1388
Reta;Interseção de Vias        1224
Declive;Curva                  1138
Rotatória                      1042
Declive                         901
Aclive                          745
Interseção de Vias;Reta         706
Aclive;Curva                    696
Curva;Aclive                    604
Retorno Regulamentado           532
Reta;Em Obras                   500
Em Obras;Reta                   370
Retorno Regulamentado;Reta      339
Name: count, dtype: int64

In [19]:
# Contagem de acidentes por classificação de acidentes
# Primeira visão da variável que originará o alvo (pedido_problematico): 
# quantos acidentes poossui a parte de classificação de acidentes 
print("\nStatus de Acidentes por Classificação de acidentes")
print(prf_acidentes_2025["classificacao_acidente"].value_counts())

Status de Acidentes por Classificação de acidentes
classificacao_acidente
Com Vítimas Feridas    56181
Sem Vítimas            11138
Com Vítimas Fatais      5209
Name: count, dtype: int64

In [20]:
# Contagem de acidentes por usos de solos
# Primeira visão da variável que originará o alvo (pedido_problematico): 
# quantos acidentes poossui a parte de usos de solos 
print("\nStatus de Acidentes por usos de solos")
print(prf_acidentes_2025["uso_solo"].value_counts())

Status de Acidentes por usos de solos
uso_solo
Não    41444
Sim    31085
Name: count, dtype: int64

#### Bloco 1 - Base tratada aos indicadores

- Objetivo: revisar a base e criar os indicadores essenciais.

* Pergunta: O que a base permite medir?


* Saida: Tabela de indicadores globais.

In [21]:
prf_acidentes_2025["acidente_grave"] = prf_acidentes_2025["classificacao_acidente"].isin(["Com Vítimas Fatais", "Com Vítimas Feridas"]).astype(int)

In [22]:
### Acidente em condição climática adversa 
prf_acidentes_2025["clima_adverso"] = prf_acidentes_2025["condicao_metereologica"].isin(["Céu Claro", "Nublado", "Chuva", "Sol", "Garoa/Chuvisco", "Ignorado", "Nevoeiro/Neblina", "Vento", "Neve"])

In [23]:
### Acidente em área urbana 
prf_acidentes_2025["area_urbana"] = (prf_acidentes_2025["uso_solo"] == "Sim").astype(int)

In [24]:
### Acidente em colisão 
prf_acidentes_2025["colisao"] = prf_acidentes_2025["tipo_acidente"].str.contains("Colisão", case=False, na=False).astype(int)

In [25]:
### Acidente em saida de pista
prf_acidentes_2025["saida_pista"] = (prf_acidentes_2025["tipo_acidente"] == "Saída de leito carroçável").astype(int)

#### Cálculo dos indicadores

In [26]:
### Total de acidentes 
total_acidentes = len(prf_acidentes_2025)

In [27]:
### Acidentes Graves 
acidentes_graves = prf_acidentes_2025["acidente_grave"].sum()

In [28]:
acidentes_fatais = (
    
    prf_acidentes_2025["classificacao_acidente"] == "Com Vítimas Fatais"
).sum()

In [29]:
### Acidentes em Climas Adversos 
acidentes_clima_adverso = prf_acidentes_2025["clima_adverso"].sum()

In [30]:
### Acidentes em Áreas Urbanas 
acidentes_area_urbana = prf_acidentes_2025["area_urbana"].sum()

In [31]:
### Acidentes com Colisões 
colisoes = prf_acidentes_2025["colisao"].sum()

In [32]:
pct_graves = acidentes_graves / total_acidentes

In [33]:
pct_fatais = acidentes_fatais / total_acidentes

#### Tabela Resumo

In [34]:
indicadores_globais = pd.DataFrame({
    
    "Indicador": [
        
        "Total de acidentes", 
        "Acidentes graves", 
        "% de acidentes graves", 
        "Acidentes em clima adverso", 
        "Acidentes em área urbana", 
        "Colisões"
    ], 
    
    "valor": [
        
        total_acidentes, 
        acidentes_graves, 
        f"{pct_graves:.1%}", 
        acidentes_clima_adverso, 
        acidentes_area_urbana, 
        colisoes
    ]
})

In [35]:
indicadores_globais

                    Indicador  valor
0          Total de acidentes  72529
1            Acidentes graves  61390
2       % de acidentes graves  84.6%
3  Acidentes em clima adverso  72529
4    Acidentes em área urbana  31085
5                    Colisões  43551

- Leitura: Os indicadores globais de acidentes representam a linha de base (baseline) da análise. Eles monstram o panorama geral da ocorrência de acidentes na base de dados e servem como referência para comparar segmentos específicos, como municípios, causas de acidentes, condições meteorológicas, tipos de pista, traçados da via e áreas urbanas ou rurais.

- Por exemplo, a porcentagem global de acidentes graves pode ser comparada com a porcentagem observada em um determinado município ou em uma determinada condição climática para identificar situações de maior risco.

#### Bloco 2 - Frequências, rankings e séries simples

In [81]:
def ranking_municipio(var): 
    
    t = (
        
        prf_acidentes_2025
        .groupby(var) 
        .agg(
            
            acidentes = ("municipio", "count"), 
            acidentes_graves = ("acidente_grave", "sum")
            
        )
        .sort_values("acidentes", ascending=False)
    )
    
    t["pct_acidentes"] = t["acidentes"] / total_acidentes 
    
    return t

ranking_municipio("municipio").head(30)

                       acidentes  acidentes_graves  pct_acidentes
municipio
BRASILIA                    1011               818           0.01
DUQUE DE CAXIAS              847               755           0.01
SAO JOSE                     761               687           0.01
GUARULHOS                    742               660           0.01
CURITIBA                     702               599           0.01
BETIM                        682               598           0.01
RECIFE                       615               516           0.01
SERRA                        579               529           0.01
PALHOCA                      568               496           0.01
JOAO PESSOA                  543               487           0.01
TERESINA                     499               416           0.01
SAO JOSE DOS PINHAIS         464               377           0.01
RIO DE JANEIRO               448               398           0.01
NOVA IGUACU                  439               386           0.01
ANGRA DOS REIS               437               410           0.01
SAO JOSE DOS CAMPOS          413               354           0.01
FEIRA DE SANTANA             403               346           0.01
ANAPOLIS                     385               312           0.01
ITAJAI                       382               337           0.01
UBERABA                      366               306           0.01
ARAQUARI                     352               327           0.00
CAMPOS DOS GOYTACAZES        350               320           0.00
UBERLANDIA                   349               284           0.00
LINHARES                     345               314           0.00
SAO GONCALO                  337               302           0.00
NATAL                        325               288           0.00
CASCAVEL                     323               282           0.00
PORTO VELHO                  319               243           0.00
SAO PAULO                    316               280           0.00
VITORIA DA CONQUISTA         314               276           0.00

In [82]:
def ranking_causa(var): 
    
    t = (
        
        prf_acidentes_2025
        .groupby(var) 
        .agg(
            
            acidentes = ("causa_acidente", "count"), 
            causas_acidentes = ("acidente_grave", "sum")
            
        )
        .sort_values("acidentes", ascending=False)
    )
    
    t["pct_acidentes"] = t["acidentes"] / total_acidentes 
    
    return t

ranking_causa("causa_acidente").head(30)

,acidentes,causas_acidentes,pct_acidentes
causa_acidente,,,
Ausência de reação do condutor,11469,9757,0.16
Reação tardia ou ineficiente do condutor,10799,9204,0.15
Acessar a via sem observar a presença dos outros veículos,7097,6483,0.10
Condutor deixou de manter distância do veículo da frente,4413,3741,0.06
Velocidade Incompatível,4088,3576,0.06
Manobra de mudança de faixa,4016,3605,0.06
Ingestão de álcool pelo condutor,3685,2226,0.05
Demais falhas mecânicas ou elétricas,3385,1579,0.05
Transitar na contramão,2475,2286,0.03
Condutor Dormindo,2116,1837,0.03
Ultrapassagem Indevida,1770,1613,0.02
Trafegar com motocicleta (ou similar) entre as faixas,1325,1290,0.02
Animais na Pista,1305,1117,0.02
Desrespeitar a preferência no cruzamento,1259,1154,0.02
Avarias e/ou desgaste excessivo no pneu,1176,1051,0.02
Chuva,1020,884,0.01
Conversão proibida,1018,957,0.01
Acesso irregular,768,691,0.01
Entrada inopinada do pedestre,667,647,0.01
Pedestre andava na pista,606,603,0.01
Mal súbito do condutor,546,508,0.01
Pista Escorregadia,545,500,0.01
Pedestre cruzava a pista fora da faixa,525,520,0.01
Transitar no Acostamento,498,459,0.01
Acumulo de água sobre o pavimento,477,398,0.01
Objeto estático sobre o leito carroçável,412,361,0.01
Frear bruscamente,358,290,0.00
Retorno proibido,325,297,0.00
Acumulo de areia ou detritos sobre o pavimento,308,272,0.00
Demais falhas na via,275,247,0.00

In [38]:
def ranking_tipos_acidentes(var):
    
    t = (
        
        prf_acidentes_2025
        .groupby(var)
        .agg(
            acidentes = ("tipo_acidente", "count"), 
            causas_acidentes = ("acidente_grave", "sum")
        )
        .sort_values("acidentes", ascending=False)
    )
    
    t["pct_acidentes"] = t["acidentes"] / total_acidentes 
    
    return t

ranking_tipos_acidentes("tipo_acidente")

                                acidentes  causas_acidentes  pct_acidentes
tipo_acidente
Colisão traseira                    14360             12190           0.20
Saída de leito carroçável           10209              8081           0.14
Colisão transversal                  9306              8500           0.13
Colisão lateral mesmo sentido        7885              6828           0.11
Tombamento                           6351              5928           0.09
Colisão com objeto                   5109              3790           0.07
Colisão frontal                      4739              4445           0.07
Queda de ocupante de veículo         3450              3375           0.05
Atropelamento de Pedestre            3057              3017           0.04
Colisão lateral sentido oposto       2152              1804           0.03
Incêndio                             1771                49           0.02
Capotamento                          1373              1165           0.02
Engavetamento                        1233               982           0.02
Atropelamento de Animal              1133               960           0.02
Eventos atípicos                      287               213           0.00
Derramamento de carga                 107                57           0.00
Sinistro pessoal de trânsito            7                 6           0.00

In [39]:
def ranking_classificacao(var): 
    
    t = (
        
        prf_acidentes_2025
        .groupby(var)
        .agg(
            
            acidentes = ("classificacao_acidente", "count"), 
            acidentes_graves = ("acidente_grave", "sum")
        ).sort_values("acidentes", ascending = False)
    )
    
    t["pct_acidentes"] = t["acidentes"] / total_acidentes 
    
    return t 

ranking_classificacao("classificacao_acidente")

                        acidentes  acidentes_graves  pct_acidentes
classificacao_acidente
Com Vítimas Feridas         56181             56181           0.77
Sem Vítimas                 11138                 0           0.15
Com Vítimas Fatais           5209              5209           0.07

In [40]:
def ranking_pista(var): 
    
    t = (
        
        prf_acidentes_2025
        .groupby(var) 
        .agg(
            
            acidentes = ("tipo_pista", "count"), 
            acidentes_graves = ("acidente_grave", "sum")
            
        )
        .sort_values("acidentes", ascending=False) 
    )
    
    t["pct_acidentes"] = t["acidentes"] / total_acidentes 
    
    return t 

ranking_pista("tipo_pista")

            acidentes  acidentes_graves  pct_acidentes
tipo_pista
Simples         34733             29441           0.48
Dupla           30782             25864           0.42
Múltipla         7014              6085           0.10

In [83]:
def ranking_tracado(var): 
    
    t = (
        
        prf_acidentes_2025 
        .groupby(var) 
        .agg(
            
            acidentes = ("tracado_via", "count"), 
            acidentes_graves = ("acidente_grave", "sum") 
            
        ).sort_values("acidentes", ascending = False)
    )
    
    t["pct_acidentes"] = t["acidentes"] / total_acidentes 
    
    return t 

ranking_tracado("tracado_via").head(30)

                              acidentes  acidentes_graves  pct_acidentes
tracado_via
Reta                              40298             33936           0.56
Curva                              8055              6879           0.11
Reta;Declive                       2059              1762           0.03
Reta;Aclive                        1963              1619           0.03
Interseção de Vias                 1735              1517           0.02
Declive;Reta                       1492              1269           0.02
Curva;Declive                      1430              1263           0.02
Aclive;Reta                        1388              1158           0.02
Reta;Interseção de Vias            1224              1091           0.02
Declive;Curva                      1138               999           0.02
Rotatória                          1042               867           0.01
Declive                             901               754           0.01
Aclive                              745               602           0.01
Interseção de Vias;Reta             706               625           0.01
Aclive;Curva                        696               591           0.01
Curva;Aclive                        604               504           0.01
Retorno Regulamentado               532               442           0.01
Reta;Em Obras                       500               425           0.01
Em Obras;Reta                       370               311           0.01
Retorno Regulamentado;Reta          339               291           0.00
Reta;Ponte                          338               279           0.00
Reta;Retorno Regulamentado          320               279           0.00
Viaduto                             269               225           0.00
Reta;Viaduto                        181               151           0.00
Interseção de Vias;Rotatória        166               131           0.00
Reta;Rotatória                      141               123           0.00
Ponte;Reta                          136               114           0.00
Curva;Interseção de Vias            126               101           0.00
Interseção de Vias;Curva            124               106           0.00
Ponte                               103                83           0.00

In [42]:
def ranking_uso_solo(var): 
    
    t = (
        
        prf_acidentes_2025
        .groupby(var) 
        .agg(
            
            acidentes = ("uso_solo", "count"), 
            acidentes_graves = ("acidente_grave", "sum") 
        )
        .sort_values("acidentes", ascending = False)
    )
    
    t["pct_acidentes"] = t["acidentes"] / total_acidentes 
    
    return t 

ranking_uso_solo("uso_solo")

          acidentes  acidentes_graves  pct_acidentes
uso_solo
Não           41444             34548           0.57
Sim           31085             26842           0.43

#### Análise dos Rankings

Leitura: Os rankings permitem identificar a distribuição dos acidentes de trânsito segundo diferentes características da ocorrência. 
A análise por município evidencia as localidades com maior concentração de acidentes, enquanto a análise por causa do acidente destaca os fatores
mais frequentemente associadoos às ocorrências.

Os rankings por condição metereológica, tipo de pista, traçado da via e uso do solo ajudam a compreender em quais condições os acidentes são mais comuns. Além disso, a coluna de acidentes graves permite avaliar não apenas a frequência das ocorrências, mas também sua severidade.

A comparação entre a participação percentual de cada categoria e os indicadores globais auxilia na identificação de padrões de risco, permitindo reconhecer os grupos que concentram maior volume de acidentes e maior quantidade de acidentes graves.

#### Municípios

Municípios: os municípios posicionados no topo do ranking concentram a maior parcela dos acidentes registrados na base. Esse resultado pode estar relacionado ao maior fluxo de veículos, densidade populacional ou presença de rodovias com elevado volume de tráfego.

#### Causa do Acidente

Causas dos acidentes: as causas mais frequentes representam os principais fatores associados às ocorrências registradas. A identificação dessas causas pode orientar ações preventivas e campanhas educativas voltadas à redução dos acidentes.

#### Condição Meteorológica

Condições meteorológicas: a distribuição dos acidentes por condição climática permite verificar se eventos como chuva, neblina ou outras condições adversas estão associados a uma maior frequência de acidentes em comparação com condições favoráveis de visibilidade.

#### Tipo de Pista e Traçado da Via

Infraestrutura viária: os rankings por tipo de pista e traçado da via permitem identificar características da infraestrutura rodoviária associadas a maior incidência de acidentes. Curvas, pistas simples ou trechos específicos podem demandar maior atenção em políticas de segurança viária.

#### Uso do Solo

Uso do solo: a comparação entre áreas urbanas e rurais auxilia na compreensão do contexto das ocorrências, indicando onde os acidentes são mais frequentes e onde podem existir maiores necessidades de intervenção e fiscalização.

#### Série Mensal

- #### Criação da coluna "mẽs" no formato Ano-Mês (ex: 2025-01)

In [65]:
# Agrupa cada acidente no seu respectivo mês, servindo como base para a analise da série temporal 
prf_acidentes_2025["mes"] = (
    
    prf_acidentes_2025["data_inversa"]
    .dt.to_period("M").astype(str)
)

- #### Agrupamento dos acidentes por mês

In [66]:

# Calcula simultaneamente a quantidade total de acidentes, 
# acidentes graves e acidentes em condições climáticas adversas 
serie_mensal = prf_acidentes_2025.groupby("mes").agg(
    
    acidentes = ("municipio", "count"), 
    acidentes_graves = ("acidente_grave", "sum"), 
    clima_adverso = ("clima_adverso", "sum")
)

- #### Cálculo do percentual mensal de acidentes graves

In [67]:
# Permite observar se a proporção de acidentes graves 
# oscila ao longo dos meses 
serie_mensal["pct_graves"] = (
    
    serie_mensal["acidentes_graves"] / 
    serie_mensal["acidentes"]
)

- #### Taxa de mortalidade

In [68]:
serie_mensal["taxa_mortalidade"] = (
    
    prf_acidentes_2025.groupby("mes")["mortos"].sum() / serie_mensal["acidentes"]
)

- #### ìndice de gravidade

In [69]:
serie_mensal["indice_gravidade"] = (
    
    prf_acidentes_2025.groupby("mes").apply(
        
        lambda prf_acidentes_2025: (prf_acidentes_2025["mortos"].sum()*3 +
                                    prf_acidentes_2025["feridos_graves"].sum() * 2
                                   + prf_acidentes_2025["feridos_leves"].sum() * 1)
    ) / serie_mensal["acidentes"]
)

/tmp/ipykernel_3094/149559206.py:3: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  prf_acidentes_2025.groupby("mes").apply(

In [70]:
serie_mensal

,acidentes,acidentes_graves,clima_adverso,pct_graves,taxa_mortalidade,indice_gravidade
mes,,,,,,
2025-01,5528,4722,5528,0.85,0.08,1.76
2025-02,5287,4465,5287,0.84,0.08,1.62
2025-03,5960,5023,5960,0.84,0.08,1.64
2025-04,5786,4910,5786,0.85,0.09,1.69
2025-05,6096,5186,6096,0.85,0.09,1.68
2025-06,6122,5163,6122,0.84,0.09,1.67
2025-07,6238,5262,6238,0.84,0.09,1.69
2025-08,6246,5247,6246,0.84,0.09,1.65
2025-09,6017,5103,6017,0.85,0.08,1.67
2025-10,6252,5328,6252,0.85,0.08,1.68
2025-11,6209,5253,6209,0.85,0.08,1.66
2025-12,6788,5728,6788,0.84,0.08,1.72

#### Limitação Importante:

- Os indicadores apresentados são agregados por mês e, portanto, não permitem identificar quais fatores específicos contribuíram para a gravidade ou mortalidade dos acidentes em cada período. Além disso, a taxa de mortalidade e o índice de gravidade são indicadores gerais e não estabelecem, isoladamente, uma relação de causa e efeito. A interpretação também depende da definição utilizada para cada indicador e da qualidade da classificação dos acidentes. Por fim, a coluna "clima_adverso" apresenta os mesmos valores da coluna "acidentes", indicando que ela pode estar representando uma medida diferente daquela apresentada na tabela anterior ou possuir um problema de definição / cálculo, devendo ser validada antes de utilizar esse indicador na análise

 - Leitura: A série mensal permite acompanhar a distribuição dos acidentes ao longo de 2025 e comparar a quantidade total de ocorrências com os acidentes graves. Observa-se uma variação no volume de acidentes entre os meses, sendo dezembro o período com maior quantidade registrada. A série serve como referência para identificar períodos de maior concentração de ocorrências e direcionar análises posteriores por município, causa, tipo de acidente e condições da via.

- #### Percentual de clima adverso

In [71]:
# Normaliza para minúsculas e remove espaços extras
prf_acidentes_2025["condicao_metereologica"] = (
    
    prf_acidentes_2025["condicao_metereologica"].str.strip().str.lower()
)

In [72]:
# Define lista de condições adversas
condicoes_adversas = ["chuva", "neblina", "vento", "tempestade", "granizo"]

In [73]:
# Cria flag binária 
prf_acidentes_2025["clima_adverso_flag"] = prf_acidentes_2025["condicao_metereologica"].apply(
    
    lambda x: 1 if x in condicoes_adversas else 0 
)

In [74]:
# Recalcula série mensal 
serie_mensal = prf_acidentes_2025.groupby("mes").agg(
    
    acidentes = ("municipio", "count"), 
    acidentes_graves = ("acidente_grave", "sum"), 
    clima_adverso = ("clima_adverso_flag", "sum")
)

In [76]:
serie_mensal["pct_clima_adverso"] = serie_mensal["clima_adverso"] / serie_mensal["acidentes"]

In [77]:
serie_mensal

         acidentes  acidentes_graves  clima_adverso  pct_clima_adverso
mes
2025-01       5528              4722            741               0.13
2025-02       5287              4465            425               0.08
2025-03       5960              5023            519               0.09
2025-04       5786              4910            561               0.10
2025-05       6096              5186            509               0.08
2025-06       6122              5163            620               0.10
2025-07       6238              5262            295               0.05
2025-08       6246              5247            400               0.06
2025-09       6017              5103            458               0.08
2025-10       6252              5328            614               0.10
2025-11       6209              5253            593               0.10
2025-12       6788              5728            807               0.12

- Uma limitação importante é que a tabela apresenta apenas os valores agregados por mês, não permitindo identificar quais tipos específicos de condições climáticas adversas estão mais relacionados aos acidentes. Além disso, o percentual de clima adverso representa a proporção de acidentes classificados nessa condição, mas não permite afirmar que o clima foi a causa direta dos acidentes. Outros fatores, como comportamento do condutor, condições da via, horário e tipo de acidente, também podem influenciar os resultados